# SquirrelDB Ruby SDK
# Generated by sdk-generator v0.1.0
# DO NOT EDIT MANUALLY

# frozen_string_literal: true

require_relative "squirreldb/types"
require_relative "squirreldb/client"
require_relative "squirreldb/storage"
require_relative "squirreldb/cache"
require_relative "squirreldb/query"

module SquirrelDB
  VERSION = "0.3.0"
end
